name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  qa:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: ffmpeg をインストール
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends ffmpeg
      - uses: astral-sh/setup-uv@v6
      - run: uv sync --locked
      - run: uv run ruff format --check
      - run: uv run ruff check
      - run: uv run pyright
      - run: uv run pytest
